import colors from '@lib/theme/colors'
import { Box, Container, Typography } from '@mui/material'
import { GetStaticProps, NextPage } from 'next'
import { useTranslation } from 'next-i18next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import Head from 'next/head'

const Rebranding: NextPage = () => {
  const { t } = useTranslation('rebranding')
  return (
    <>
      <Head>
        <title>{t('title')}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="xl">
        <Box textAlign="center" mt={24}>
          <Typography variant="h1">{t('title')}</Typography>
          <Container maxWidth="md" sx={{ my: 8 }}>
            <Typography variant="subtitle1">{t('subtitle1')}</Typography>
            <Typography variant="subtitle1" mt={4}>{t('subtitle2')}</Typography>
          </Container>
          <Box height="650px" borderRadius={5} bgcolor={colors.neutralBlack}/>
        </Box>
        <Box textAlign="center" mt={18} mb={10}>
          <Typography variant="h3" sx={{whiteSpace: "pre-wrap"}}>{t('inNumbersSection.heading')}</Typography>
        </Box>
      </Container>
    </>
  )
}

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale ?? 'en', [
        'rebranding',
      ])),
    },
  }
}

export default Rebranding
